# Generated by Django 2.0.7 on 2018-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HallModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('exhibit', models.ForeignKey(on_delete='NULL', related_name='images', to='museum.ExhibitModel')),
            ],
        ),
        migrations.AddField(
            model_name='exhibitmodel',
            name='hall',
            field=models.ForeignKey(on_delete='RESTRICT', related_name='exhibits', to='museum.HallModel'),
        ),
    ]
