# Generated by Django 2.0.7 on 2018-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20180710_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitmodel',
            options={'verbose_name': 'Экспонат', 'verbose_name_plural': 'Экспонаты'},
        ),
        migrations.AlterModelOptions(
            name='hallmodel',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='picturemodel',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='exhibitmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='exhibitmodel',
            name='country',
            field=models.CharField(default='ru', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitmodel',
            name='epoch',
            field=models.CharField(default='XIX век', max_length=32),
            preserve_default=False,
        ),
    ]
