# Generated by Django 2.0.7 on 2018-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20180710_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitmodel',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='exhibitmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exhibitmodel',
            name='epoch',
            field=models.CharField(max_length=32, verbose_name='Год(-ы)'),
        ),
        migrations.AlterField(
            model_name='exhibitmodel',
            name='hall',
            field=models.ForeignKey(on_delete='RESTRICT', related_name='exhibits', to='museum.HallModel', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='exhibitmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hallmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='exhibit',
            field=models.ForeignKey(on_delete='NULL', related_name='images', to='museum.ExhibitModel', verbose_name='Экспонат'),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
