# Generated by Django 2.0.7 on 2018-07-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20180711_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='epoch',
            field=models.CharField(max_length=50, null=True, verbose_name='Эпоха'),
        ),
        migrations.AddField(
            model_name='hall',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='country',
            field=models.CharField(max_length=2, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='epoch',
            field=models.CharField(max_length=32, null=True, verbose_name='Год(-ы)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
