# Generated by Django 2.0.7 on 2018-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_auto_20180712_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='epoch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Эпоха'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(default='Pre-NULL', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
