# Generated by Django 2.0.7 on 2018-07-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_auto_20180712_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name': 'экспонат', 'verbose_name_plural': 'экспонаты'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'зал', 'verbose_name_plural': 'залы'},
        ),
    ]
