# Generated by Django 2.0.7 on 2018-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_auto_20180712_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='epoch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='эпоха'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='номер'),
        ),
    ]
