# Generated by Django 2.0.7 on 2018-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_auto_20180712_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='country',
            field=models.CharField(max_length=2, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='epoch',
            field=models.CharField(max_length=32, null=True, verbose_name='год(-ы)'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete='RESTRICT', related_name='exhibits', to='museum.Hall', verbose_name='зал'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='exhibit',
            field=models.ForeignKey(on_delete='NULL', related_name='images', to='museum.Exhibit', verbose_name='экспонат'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='изображение'),
        ),
    ]
