# Generated by Django 2.0.7 on 2018-07-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_auto_20180712_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='order_number',
            field=models.IntegerField(default=1, max_length=5, unique=True, verbose_name='порядковый номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='epoch',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='год(-ы)'),
        ),
    ]
