# Generated by Django 2.0.7 on 2018-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_auto_20180712_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='order_number',
            field=models.IntegerField(max_length=5, verbose_name='порядковый номер'),
        ),
    ]
