# Generated by Django 2.0.7 on 2018-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_auto_20180712_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='order_number',
            field=models.IntegerField(verbose_name='порядковый номер'),
        ),
    ]
