# Generated by Django 2.0.7 on 2018-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_auto_20180712_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='изображение'),
        ),
    ]
