# Generated by Django 2.0.7 on 2018-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_auto_20180712_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='описание'),
        ),
    ]
