# Generated by Django 2.0.7 on 2018-07-15 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_auto_20180712_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('message', models.TextField(verbose_name='описание')),
                ('sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'предлагаемый экспонат',
                'verbose_name_plural': 'предлагаемые экспонаты',
            },
        ),
    ]
