# Generated by Django 2.0.7 on 2018-07-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
