# Generated by Django 2.0.7 on 2018-07-17 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_picture_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя отправителя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('message', models.TextField(verbose_name='описание')),
                ('sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'предлагаемый экспонат',
                'verbose_name_plural': 'предлагаемые экспонаты',
            },
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='код страны'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='epoch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='год(-ы)'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='order_number',
            field=models.IntegerField(verbose_name='год (для сортировки)'),
        ),
    ]
