# Generated by Django 2.0.7 on 2018-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0014_auto_20180716_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(height_field='height', upload_to='img', verbose_name='изображение', width_field='width'),
        ),
    ]
