# Generated by Django 2.0.7 on 2018-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0015_auto_20180716_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='height',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='width',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='изображение'),
        ),
    ]
